### ISSUE TITLE
autorun fails placing steam

### ISSUE THREAD

**Issue by aeosynth** [conformal/spectrwm#135]
i have `autorun = ws[2]:steam` in my config, but steam shows up in workspace 1. using `quirk[Steam] = WS[2]` works fine.

**Comment by LordReg** [comment]
spectrwm uses libswmhack.so to map windows created by a process to a specific workspace.  If libswmhack.so was built for x86_64, then it will not work with Steam since it is 32-bit.
You can workaround this issue by building a 32-bit libswmhack.so and then create and autorun a script similar to this:
```
#!/bin/sh
LD_PRELOAD=/usr/local/lib/libswmhack.so.0.0:/usr/local/lib32/libswmhack.so.0.0 /usr/bin/steam
```

**Comment by aeosynth** [comment]
thanks for the info. i will just use `quirk`.
