### ISSUE TITLE
Implement _NET_WM_WINDOW_TYPE_DOCK

### ISSUE THREAD

**Issue by hkkmori** [conformal/spectrwm#151]
Hi,

I would like to use a gtk panel like lxpanel for instance, instead of the default bar .
Maybe we need to reserve space for the panel for this , but i don't know the complete method.

Thanks.

**Comment by seschwar** [comment]
I also would like to use an EWMH compliant third-party panel. However the [current handling of docks](https://github.com/conformal/spectrwm/blob/master/spectrwm.c#L1532) leaves much to be desired.

Docks are treated as floating windows. However this means that you can accidentally focus, move or resize them. Additional `NOFOCUS*` hints are not enough since they don't fully prevent the dock from being focused. For example the dock still can be focused, moved and resized with the mouse.

**Comment by seschwar** [comment]
#147 seems to address this.

**Comment by seschwar** [comment]
I don't find `region` and `quirk[...] = FLOAT + ANYWHERE + MINIMALBORDER + NOFOCUSCYCLE + NOFOCUSONMAP` satisfactory. The quirk is not enough because you still can focus and move the dock with the mouse. It can be quite annoying when that happens by accident. And manually setting the region gets tedious if you dynamically change your screen configuration in order to give presentations for example.

It would be nice if spectrwm would be smarter about _NET_WM_WINDOW_TYPE_DOCK windows out of the box.

**Comment by marcopeereboom** [comment]
That's a fair request.  I'll reopen issue and see if someone sends in a PR.
