### ISSUE TITLE
Workspaces independent to regions

### ISSUE THREAD

**Issue by xaionaro** [conformal/spectrwm#165]
Hello.

I'm trying to migrate to spectrwm from dwm. And I used to have separate workspaces on every region (screen). Can I enable the same behavior in spectrwm?

**Comment by LordReg** [comment]
I am unclear how you envision this working on spectrwm.  Each workspace is considered a unique EWMH 'desktop'  If there were multiple 'workspace 1', for example, it would create conflicts.  If you really wanted separate workspaces on every region, perhaps there could be a config flag that mapped a new set of uniquely indexed workspaces to each region.  For example, with workspace_limit=10, region 1 would have ws1-ws10, region 2 would have ws11-20, etc.  The workspace action bindings (ws_n, mvws_n) could map to the 'nth workspace' relative to the focused region.  This would require region workspace swapping to work in a different manner than it does now.  Instead of literally swapping workspaces, the windows would need to swapped between the visible workspaces.

I haven't used dwm, but as I understand, it uses 'tags' not 'workspaces' and you choose which tagged windows are in view.  This is a different than the discrete workspace concept that spectrwm employs.

Please elaborate on your vision of the functionality and benefit of this feature.  It seems to me it would add unnecessary complication and confusion.

**Comment by xaionaro** [comment]
> Please elaborate on your vision of the functionality and benefit of this feature. It seems to me it would add unnecessary complication and confusion.

Sorry, but I don't know technical details of spectrwm. I just need this feature as a potential user. I can understand if somebody will just reject this issue. BTW, this sounds reasonable as for me:

> For example, with workspace_limit=10, region 1 would have ws1-ws10, region 2 would have ws11-20, etc.

Benefit is that I can use my behavior patterns (that are best for me right now) in spectrwm. I don't like how spectrwm offers me to work right now — it's subjectively not convenient.

**Comment by LordReg** [comment]
> Benefit is that I can use my behavior patterns (that are best for me right now) in spectrwm. I don't like how spectrwm offers me to work right now — it's subjectively not convenient.
So you simply want to have unique workspaces on each region with the same set of workspace bindings?

**Comment by xaionaro** [comment]
> So you simply want to have unique workspaces on each region with the same set of workspace bindings?

Yes. Sorry if I explained myself unclear :(

**Comment by marcopeereboom** [comment]
This sounds very complicated. We'll take a PR if someone wants to add this.
