### ISSUE TITLE
Window disappears on 5 clients in [0|2] layout

### ISSUE THREAD

**Issue by marshallmason** [conformal/spectrwm#196]
I was goofing around with the number of windows in the master and stack areas and found some strange behavior in this particular case. I had 5 windows open, I dropped the master area to 0 with Mod-period, and increased the stack area to 1 with Mod-Shift-comma. The lowest client in the stack area disappeared.

Also, some of the windows in the stack area are misaligned. The borders don't line up. This is the case whether or not there is a master area. I've tried to reproduce this with only terminal windows, and it lines up correctly. I only got this problem when I had a Chromium browser in the mix.

![missing_window](https://user-images.githubusercontent.com/13948591/36931359-d7c68e62-1e68-11e8-992c-d70cdb586728.png)

Using Version 3.1.0 on Arch Linux.

**Comment by LordReg** [comment]
The 'misalignment' is because spectrwm tries to align the height of each window to the WM_NORMAL_HINTS resize increment as it stacks each window.  The width of the master area is aligned according to the first master area window.  Terminals typically define a resize increment, Chromium does not.

Fixed the disappearing window issue on the latest commit.
