### ISSUE TITLE
Spectrwm on Thinkpad X1 Carbon sporadically hangs when attached to dock station

### ISSUE THREAD

**Issue by izinovik** [conformal/spectrwm#240]
From time to time spectrwm hangs when I attach my Thinkpad X1 Carbon to docking station with two connected monitors. It starts attaching new monitors and picture on on of them start flickering, keyboard stop react on key strokes (I cannot restart spectrwm or Xorg). This happens from time to time, sometimes connection to dock station ends in spectrwm hang, sometimes everything goes fine.

I have no logs to show, but if some of developers will guide me how can I enable logging for spectrwm I'm willing to help.

This happens on Ubuntu 18.04 with spectrwm 3.1.0 and Xorg 7.7+19ubuntu7.1

**Comment by marcopeereboom** [comment]
Sounds like an xrandr issue of sorts. Does this still happen with the latest spectrwm version though?

**Comment by izinovik** [comment]
Ubuntu repositories do not have latest spectrwm 3.2.0. Have to wait till it gets available.

**Comment by marcopeereboom** [comment]
Please reopen if this still occurs.

**Comment by twelveseas** [comment]
first time using spectrwm, have this bug
distro - void 
Xorg version - 7.6_5 
xorg-server version - 1.20.10_3 
spectrwm version - 3.4.1
intel hd graphics 620
intel's xf86 driver (yes i want it, might be its fault i think)
kernel - 5.4
~~~~~~~~
tried both - binary from the repo and self compiled master (not sure here, just git cloned the github page), problem occurs on both 
~
how to reproduce  (very easy on my machine):
1. start x11 with spectrwm
2. open some windows
3. (i have a laptop that connected to a monitor) either disable one of the outputs with xrandr --output eDP1 or HDMI1 --off OR enable one of them with in my case xrandr --output HDMI1 --auto --left-of eDP1 (tried specifying refresh rate, wont help)
4. get a good chance of spectrwm starting to blink with windows, then you cant swith tags or do anything besides killing Xorg. PS. sometimes it starts the blinking, but allows you to switch to a different tag and then its like nothing happen.

**Comment by twelveseas** [comment]
i think i found the problem

initially i named all 10 tags/workspaces in japanese, all hiragana characters, got rid of that and now it doesnt hang, nothing else changed, didnt even reboot since, bar font is default (fixed or terminus?). 

Also when there is more that one workspace eg i have some windows on the second workspace too, disabling my laptops screen leads to blinking on the second monitor, like it cant choose either between layouts or workspace and switches then super fast, but it goes away after you switch to a different workspace.

**Comment by twelveseas** [comment]
i thought maybe its not japanese, but unicode (non english characters in general), and i had window_name_enabled=1 in the config so that windows's name is displayed on the bar, opened two chromium windows, typed random russian characters into duckduckgo so that both windows on the first workspace lead to russian letters on the bar, disabled/enabled laptops display ~10 times and it crashed.

now i disabled window_name_enabled and started to disable/enable the display. 
did that ~50 times and cant get it to crash, it still does start to switch layouts(or workspaces) madly every single time thought. 

sad because i liked hiragana and window names on the bar
