### ISSUE TITLE
The need of baraction.sh for linux

### ISSUE THREAD

**Issue by Franchium** [conformal/spectrwm#267]
spectrwm need default baraction script for linux, because it's not easy to configure by the user itself.

**Comment by marcopeereboom** [comment]
We'll take a pr.

**Comment by LordReg** [comment]
We could just include a minimally modified version of the openbsd baraction.sh in the linux/ dir?

**Comment by marcopeereboom** [comment]
Yep, works for me. We probably should do one for all supported OS'. PRs welcome.

**Comment by andreabolognani** [comment]
Up until 2014, Debian was carrying two patches to `baraction.sh`: one (`U01-remove-bash-assumptions.diff`) which removed bashisms from the script and made it more amendable to further changes, and another one (`D02-remove-openbsd-assumptions.diff`) which replaced all the OpenBSD-specific commands and behaviors with their Linux equivalents.

This is the commit which dropped said patches: https://salsa.debian.org/debian/spectrwm/commit/3206bb6784cf610f6cf6a1c2d3fbef8dc05691ee. The script hasn't changed a whole lot in the meantime, so the patches probably still apply with very minimal massaging.

I didn't dig through my mails to find the conversation, but I remember that at some point I tried to get the first patch upstream without much success. @marcopeereboom, would you now consider merging `U01-remove-bash-assumptions.diff` if I refreshed it and ensured it applied cleanly?

If that's the case, brushing up `D02-remove-openbsd-assumptions.diff` as well shouldn't be a massive amount of work, and if we had a `linux/baraction.sh` that only differs in that way from the regular `baraction.sh` I think the situation would be maintainable enough in the long run.

If the above sounds like a plan, I can prepare a PR.

**Comment by LordReg** [comment]
baraction.sh doesn't need to aim to be universal. A PR to add linux/baraction.sh is sufficient and the same can be done for each of the other supported OSs.  If those two patches produce a baraction.sh that runs on debian, that would probably be a decent initial linux/baraction.sh.

**Comment by andreabolognani** [comment]
Agreed that having a single `baraction.sh` that works on all OS is probably more trouble than it's worth, and to be clear I'm not trying to go down that route.

The reason why I always maintained those two patches as separate is that the second one is Debian (well, Linux) specific and wouldn't make sense at all on OpenBSD, but the first one merely makes the script portable to more shells and moves all the OS-specific bits to a single place, so that patching the script to work on other OSs is easier.

Importing a `linux/baraction.sh` that has both those patches applied, while leaving the main `baraction.sh` untouched, would be far too messy IMHO, especially when it comes to merging improvements and fixes back and forth, and I wouldn't want to maintain that.

Does that make sense? I can prepare a small PR that only applies the first patch as a starting point.

**Comment by LordReg** [comment]
Each example baraction.sh need not be in sync with the OpenBSD example but I see no harm in a PR that simplifies porting the current baraction.sh as long as it doesn't break on the current OpenBSD release. @marcopeereboom ?

**Comment by andreabolognani** [comment]
Created https://github.com/conformal/spectrwm/pull/274 taking care of this.

**Comment by marcopeereboom** [comment]
The OpenBSD script is fine and can be left alone. The Linux one is really up to the first person that makes one nominally work. I don't care which Linux flavor is used since the script will probably need modifying anyway to accommodate the various flavors.
