### ISSUE TITLE
rg_move_next window failed

### ISSUE THREAD

**Issue by jerome-diver** [conformal/spectrwm#272]
i config:
```
 bind[rg_move_next] = MOD+Shift+RIght
```
But when i open pycharm in region 1 and from pycharm i open a separate window for what ever (terminal or commit status...), if i want to move this window to region 2, normally select it (move mouse on it) then MOD+Shift+Rigth should move this window to region 2.
Instead, the full IDE pycharm is moving (and not only this window alone).

**Comment by LordReg** [comment]
When pycharm *View Mode* is set to *float*, it creates the separate windows as *transient* windows. 
By design, spectrwm aims to keep transient windows on the same workspace as their referenced target windows.

If you set *View Mode* to *window* in pycharm, the separate windows are instead created as normal top-level windows.  Such windows can be moved independently to other workspaces.
If you prefer the normal windows to automatically float, you can add a quirk to your spectrwm.conf such as:
`quirk[jetbrains-pycharm-ce:jetbrains-pycharm-ce:Terminal] = FLOAT`
