### ISSUE TITLE
autorun xterm opens on wrong workspace

### ISSUE THREAD

**Issue by mvhulten** [conformal/spectrwm#281]
At login I want

`autorun = ws[2]:xterm`

but `xterm` opens on workspace 1 instead.  Same for urxvt, but other programs do open on the specified workspace.  To be sure, I removed quirks with `quirk[XTerm] = NONE`, but xterm still opens on workspace 1 at start-of-day.

I am using spectrwm 3.3.0 on OpenBSD.

**Comment by bket** [comment]
On OpenBSD `xterm(1)` has the setgid bit set, and tracing is limited for setuid/setgid programs. Users may only trace their own processes and only the superuser can trace setuid or setgid programs. As a result `libswmhack` is unable to intercept specific calls, i.e. `XCreateWindow(3)`, leading to the expected behaviour of ``autorun = ws[2]:xterm`` not being met.

I'm using the workaround below:

```
autorun = ws[2]:xterm -name ws2
quirk[XTerm:ws2] = WS[2]
```

For reference purposes; I tested two alternative terminal emulators with `autorun` in `.spectrwm.conf`:
- ``urxvt`` (x11/rxvt-unicode in ports) also has the setgid bit set, thus acting similar as ``xterm(1)``. A similar workaround as above is needed.
- ``st`` (x11/st in ports) does not have the setgid bit set and works. No workaround is needed.

I also tested with ``autorun = ws[2]:xterm`` AND removing the setgid bit from ``xterm(1)``. In line with the above this changes behaviour, and no longer needs the workaround. Please note that removing the setgid bit is probably a **BAD** idea.

Assuming that this a feature on OpenBSD we could opt for describing this behaviour in the manpage.

**Comment by mvhulten** [comment]
Yes, this work-around works!  The addition in the man page is useful, thanks.

It did introduce another issue—unrelated to spectrwm—of that xrdb settings are not used when starting xterm with an option.  Concretely, `xterm*faceSize` is always set (to 14 according to `~/.Xdefaults`).  Then when starting `xterm`, this value is applied (big letters).  However, when starting `xterm -name ws2`, this value is ignored (small letters; even though xrdb(1) tells me it is set).

**Comment by mvhulten** [comment]
I don't have the xrdb issue with urxvt.  In addition, I added quirks for that:

    autorun = ws[2]:urxvtc -name ws2
    quirk[URxvt:ws2] = WS[2]

and for other workspaces.
