### ISSUE TITLE
yo, so i have some questions about the bar

### ISSUE THREAD

**Issue by Danilopereira82** [conformal/spectrwm#316]
first
i think you could make the bar stop processing the script if the bar is hidden
like, i'm not seeing the bar, why keep the script running?

second
emojis, i would like to have some emojis in the bar for status but nothing works,
in bar_font_pua i'm using typicons because no other font works to show the emojis
and even using typicons i can only use some very simple emojis

i've been talking in the IRC chat asking for help about this
but the only thing i could get to work was some simple emojis from typicons

and what is xfd and how to use it?
i can't get any information about the font

**Comment by mschilli87** [comment]
@Danilopereira82:
> i think you could make the bar stop processing the script if the bar is hidden
like, i'm not seeing the bar, why keep the script running?

Somehow I cannot find your PR with the suggested fix. It reads like you know exactly what to do and it would be easy. :wink:
Or did you forget this is run by volunteers for free and not a company that you pay?

To be clear, I'm not a developer of spectrwm and not associated with the project. But if I where, I'd be highly discouraged by your feedback. It comes across demanding and not like a suggestion to somebody how they could further improve the awesome thing they provide to you for free.

> i can't get any information about the font

Maybe you can't get any information because you didn't look hard enough? :wink:
At least try to show that you made an effort, too, by telling us where you looked and what kind of information you are looking for.

Don't get me wrong, maybe I'm just in a cranky mood but I see a lot of input to the few guys working on this in their spare time and most of it is not particularly constructive. So I felt compelled to speak up for them. Hope I didn't step on anyones toes.

Feel free to delete this comment and accept my apology if this is not appreciated.

**Comment by Danilopereira82** [comment]
god fuckin dammit man
what a fuckin retard
shut the fuck up

telling to not run the script while the bar is not visible is not a suggestion
i am really demanding stuff, because you know, i am the ceo of demanding you fuckin retard

and i can't get any information because i didn't read the man page
i didn't run the program with --help
i didn't search about it
i just came here DEMANDING THINGS 

go fuck yourself
