### ISSUE TITLE
Quirk doesn't work on IntelliJ IDEA

### ISSUE THREAD

**Issue by Harjuu** [conformal/spectrwm#326]
xprop output: `WM_CLASS(STRING) = "jetbrains-idea", "jetbrains-idea"`

in spectrwm.conf: `quirk[jetbrains-idea:jetbrains-idea] = FLOAT`

Man-page doesn't say anything about '-' needing to be escaped in any way so I don't see what the problem could be. Other quirks for things like Galculator work without any problems. 

Same problem applies to windows opened by IDEA when I tried making them float.

**Comment by LordReg** [comment]
I tested this and the issue isn't your quirk or spectrwm. spectrwm does indeed float the window.  The issue is the app immediately sends a (EWMH) ClientMessage request to remove _NET_WM_STATE_ABOVE from _NET_WM_STATE on its window, which tells spectrwm to unfloat it.

There may be some flag/setting to disable that behavior in the app

**Comment by fimmind** [comment]
@LordReg, it looks like CGoban has the same problem (It is opened in tiling mode, ignoring quirks, and, even if I switch it to floating mode manually by `floating_toggle`, it returns to tiling mode after if I go to another workspace and then return). But there is an interesting moment: CGoban stays floaing in `i3wm` even though I haven't configured it in any special way. Are you sure there is no way to fix this problem in `spectrwm`?
