### ISSUE TITLE
Scratchpad functionality like xmonad

### ISSUE THREAD

**Issue by Harjuu** [conformal/spectrwm#331]
Hi. 

Would it be possible to have a form of scratchpad functionality where you could bind a key to open a floating window (terminal/any program) that is workspace independent? I really like the iconify/uniconify functionality but I really dislike how the window gets iconified to the specific workspace. 

I would for example like to be able to show and hide Spotify on any workspace without needing to have a dedicated workspace for it. This would also be very useful for terminals.

This would basically function like iconify without being bound to a specific workspace, and also have the ability to show/hide with a hotkey instead of having to go through dmenu and search for the window.

**Comment by LordReg** [comment]
It isn't currently an integrated feature, but it is possible to do via EWMH. A custom *uniconify* script can be bound to a key combination that lists all iconified windows on all workspaces and handles the selection using `wmctrl`.

For example: https://github.com/Excerion/dswitcher
`wmctrl -i -R` can be used instead of `wmctrl -i -a` to tell spectrwm to move a given window id to the current workspace and uniconify.

note that you may need to use the latest spectrwm git for those wmctrl commands to work.

The toggle show/hide behavior you describe could also be done via a script with xdotool/wmctrl.

**Comment by Harjuu** [comment]
The latest version being 3.3.0, correct?

I tried the script you linked and changed to `wmctrl -i -R`, which does move the window to the correct workspace but it doesn't uniconify.

**Comment by LordReg** [comment]
> The latest version being 3.3.0, correct?

I meant the fix is newer than 3.3.0 so you will need to build/run the latest code in this repository for it to work.  If you happen to run Arch Linux there is spectrwm-git in the AUR.

**Comment by Provessor** [comment]
@LordReg you mentioned "It isn't currently an integrated feature", does this mean a well written patch would be accepted or would an external script always be preferred?

**Comment by marcopeereboom** [comment]
It should work. I am going to roll a release soon so please reopen if it is still an issue.
