### ISSUE TITLE
Wide Nerd Icons Glyphs are cut in Half in Bar

### ISSUE THREAD

**Issue by shans10** [conformal/spectrwm#357]
**OS:** Arch Linux
**Spectrwm Version:** 3.4.0
**Bar Font**: Iosevka Nerd Font

I just updated spectrwm to version 3.4.0 a few minutes ago and now my bar icons are cut in half, before the update they were working fine.

**Here's a screenshot for before and after update**

_Before Update_
![screenshot](https://user-images.githubusercontent.com/28944997/85217035-cee23e80-b3a9-11ea-82e7-23c1b5ab5eb8.jpg)

_After Update_
![Screenshot_2020-06-21-29_1366x17](https://user-images.githubusercontent.com/28944997/85217045-e8838600-b3a9-11ea-9b1c-d4ab3eea0ed5.png)

**Comment by LordReg** [comment]
Looks like a side effect of this fix: 2657c691df74cd97b39922faa7d733e3035d757b. It appears something more needs to be figured into the character width/offset.

**Comment by shans10** [comment]
> Looks like a side effect of this fix: [2657c69](https://github.com/conformal/spectrwm/commit/2657c691df74cd97b39922faa7d733e3035d757b). It appears something more needs to be figured into the character width/offset.

Yes looks like it and also there is extra space before the icon after the new changes which is not there in the above screenshot!

**Comment by LordReg** [comment]
I checked the font metrics of the Iosevka Nerd Font glyphs in your screenshots and the positioning is actually correct in the *After Update* screenshot.

The issue in your *After Update* screenshot is due to a bug in the Nerd Font patching procedure. The *advance-width* of each icon glyph is set too small. As a result, the glyphs overlap. You can see the same behavior in other programs such as libreoffice, polybar, inkscape, conky, etc. Other icon fonts (such as Typicons) work fine since they set *advance-width* wide enough to not have overlap.

Possible solutions:
- Wait for https://github.com/ryanoasis/nerd-fonts/issues/442 to be fixed (or rebuild Nerd Fonts yourself with the provided patch that fixes the *advance-width*.)
- Use `Iosevka Nerd Font Mono`.
The *Mono* variant scales down the wide icon glyphs to be monospace. Since the icons are in the Private Use Area, you can use `bar_font_pua` in your `spectrwm.conf` to increase the size of just those glyphs.

For example:
```
bar_font = Iosevka Nerd Font Mono:pixelsize=14:antialias=true
bar_font_pua = Iosevka Nerd Font Mono:pixelsize=28:antialias=true
```

**Comment by shans10** [comment]
> I checked the font metrics of the Iosevka Nerd Font glyphs in your screenshots and the positioning is actually correct in the _After Update_ screenshot.
> 
> The issue in your _After Update_ screenshot is due to a bug in the Nerd Font patching procedure. The _advance-width_ of each icon glyph is set too small. As a result, the glyphs overlap. You can see the same behavior in other programs such as libreoffice, polybar, inkscape, conky, etc. Other icon fonts (such as Typicons) work fine since they set _advance-width_ wide enough to not have overlap.
> 
> Possible solutions:
> 
> * Wait for [ryanoasis/nerd-fonts#442](https://github.com/ryanoasis/nerd-fonts/issues/442) to be fixed (or rebuild Nerd Fonts yourself with the provided patch that fixes the _advance-width_.)
> * Use `Iosevka Nerd Font Mono`.
>   The _Mono_ variant scales down the wide icon glyphs to be monospace. Since the icons are in the Private Use Area, you can use `bar_font_pua` in your `spectrwm.conf` to increase the size of just those glyphs.
> 
> For example:
> 
> ```
> bar_font = Iosevka Nerd Font Mono:pixelsize=14:antialias=true
> bar_font_pua = Iosevka Nerd Font Mono:pixelsize=28:antialias=true
> ```

Thank you for looking into it. I tried it and the issue is solved with mono version of the font but I will wait for the fonts to be fixed because in mono fonts some icons become too big and some too small.
