### ISSUE TITLE
Frequent Xorg crashes

### ISSUE THREAD

**Issue by cpnfeeny** [conformal/spectrwm#364]
Hi,

Loving spectrwm so far, but I'm getting lots of X crashes that send me back to the command line. Here are the relevant lines from the log:

```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  1072
  Current serial number in output stream:  65050
X connection to :0 broken (explicit kill or server shutdown).

```
```
uname -r 
5.7.5-arch1-1

```
```
spectrwm -v 
spectrwm 3.4.0 Build: 3.4.0
```

Any ideas how this can be fixed? 

Thanks.

**Comment by LordReg** [comment]
Hi,
I suggest trying the AUR/spectrwm-git package to see if you still have the issue.  A few bugs have been fixed since 3.4.0 but the crash may be due to a modification made by the `community/spectrwm 3.4.0-2` package: https://github.com/conformal/spectrwm/issues/363#issuecomment-649420476
Let me know if you still experience the issue with the latest version and I'll look into it.

**Comment by marcopeereboom** [comment]
This does seem like an upstream induced crash. Please reopen if that is not the case.

**Comment by Blarse** [comment]
I have the same problem, but my system is:
`5.7.7-arch1-1; spectrwm 3.4.1 Build: c8bbe51f2534db20d9c3e6598a99d28d48f8c224`

I couldn't find anything in the log files and after crash Xorg says `Server terminated successfully`.

I suppose the problem is somehow related to either spectrwm config or firefox.

**Comment by Blarse** [comment]
[spectrwm_crash.log](https://github.com/conformal/spectrwm/files/4879637/spectrwm_crash.log)

Just got a crash log.

**Comment by Blarse** [comment]
So it looks like I've found a solution. The problem was with the Emoji fonts I guess. In order to solve this problem you need to install aur:[ttf-symbola](https://aur.archlinux.org/packages/ttf-symbola/).

Some helpful github issues:
LukeSmithxyz/voidrice#242
LukeSmithxyz/voidrice#284
