### ISSUE TITLE
XQuartz quits and keeps restarting when running spectrwm

### ISSUE THREAD

**Issue by lukasepple** [conformal/spectrwm#37]
I compiled and installed spectrwm on Mac OS X 10.9.2 with Homebrew and xquartz.
My `.xinitrc` is:
```
exec spectrwm
```

Then I start XQuartz.app and it immediately quits and keeps restarting and quitting until I delete `.xinitrc`.
This is the Makefile I used: <https://gist.github.com/lukasepple/3ab560a8e406845ec537>

**Comment by jaumemk** [comment]
Hi, 
I dont know if this still happening to you, maybe will help others.
Same happened to me and I fixed it this way. Instead of using:
`exec spectrwm`
In my `.xinitrc` file, I use: 
`exec /usr/local/bin/spectrwm`

Then, check your system processes (w/ top command or Activity Monitor), if you setup your X11 preferences to Full Screen Mode, maybe it's runging in background in Full Screen Mode, try this: `Option+Command+A` to toggle wm.

**Comment by marcopeereboom** [comment]
That is the correct usage @jaumemk. Unfortunately OSXQuartz is a bit finicky; I know I suffer daily.
