### ISSUE TITLE
[feature request] System tray by default

### ISSUE THREAD

**Issue by ajP89** [conformal/spectrwm#374]
PLZ add a built-in system tray in the bar.

**Comment by voidpin** [comment]
![bar-scrot](https://user-images.githubusercontent.com/35956139/89650432-ba5af680-d8c2-11ea-8a21-90c60fb814aa.png)

Actually, I'd be happy if I could list all open windows instead of only the active one. It would be kind of a system tray and good enough for most of the use cases ;)

**Comment by mschilli87** [comment]
I don't see why anybody should decide how such features should look be implemented for everyone and then spend time maintaining it. What is the problem to write a (tiny) `bar_action` script that parsed `wmctrl -l` or something? This comes at the additional advantage that one tray implementation can be used with many window managers instead of everyone writing and maintaining their own.
Probably I'm not really getting what exactly is requested here. Maybe you want to elaborate in case it's not just me? :wink:

**Comment by marcopeereboom** [comment]
Someone is welcome to send us a PR that does not change any defaults. There are several third party trays you can use as well.

That said, why on earth do you need a system tray? It adds nothing but worthless distractions.

**Comment by voidpin** [comment]
@mschilli87 I guess you misunderstood me or, I didn't express myself well enough.
I was simply pointing out that it's already **nearly** possible to achieve something similar. If I'd combine it with your suggestion than its perfectly possible.
@marcopeereboom I agree, that's why I use `spectrwm`, I don't need those features. Actually, I was using `frankenwm` without any bar, just missed the clock and workspace indicator. I'm happy with it.
