### ISSUE TITLE
Chromium not regaining focus after window with same class closes

### ISSUE THREAD

**Issue by smhmd** [conformal/spectrwm#384]
**Reproduce:**
1. Open `chromium` (new tab, for instance.)
1. `Ctrl+s` to save webpage.
1. Close the save dialogue (which has the same window `class` and `instance` but not `name`) through `bind[quit]` not cancel button.
1. `chromium` will not regain focus and will require clicking or `search_win` to be focused.

**Comment by masumhabib** [comment]
Hi LordReg,

I was having the same problem and was able to narrow down the problem to commit # [73ad871291aaa51ed6993c9a01e6e8bcf0daee27 ](https://github.com/conformal/spectrwm/commit/73ad871291aaa51ed6993c9a01e6e8bcf0daee27) -- before this commit, everything was fine.


Hopefully, this helps a bit.

**Comment by qsmodo** [comment]
@masumhabib It seems that a workaround is to deactivate these four lines in the source:

https://github.com/conformal/spectrwm/blob/f20160fc106d6eb9ac3fc611653b7ef3c61ff00e/spectrwm.c#L11276-L11279

Thus transient windows are no longer handled in a special manner. The side-effect is that dialog windows become tiled, but it's definitely a deal to me while this issue is not solved.
