### ISSUE TITLE
Spotify float quirk not working

### ISSUE THREAD

**Issue by Harjuu** [conformal/spectrwm#385]
I have tried both `quirk[Spotify] = FLOAT` and `quirk[Spotify.spotify] = FLOAT` but none of them make spotify floating by default.

Output of xprop on Spotify: `WM_CLASS(STRING) = "spotify", "Spotify"`

Is this the same problem as with IntelliJ, where Spotify sends a request to remove _NET_WM_STATE_ABOVE? And is there no work-around for this?

**Comment by marcopeereboom** [comment]
@LordReg?

**Comment by LordReg** [comment]
The issue is different than the IntelliJ issue. This is a [known ICCCM-compliance issue](https://community.spotify.com/t5/Desktop-Linux/WM-CLASS-window-property-on-Linux/m-p/1427287/highlight/true#M4226) with Spotify. It sets `WM_CLASS` *after* it tries to map its window. `WM_CLASS` is not set at the moment spectrwm manages the window so it's not possible to match the quirk. A [workaround exists](https://github.com/dasJ/spotifywm) which intercepts the MapWindow call and sets WM_CLASS first.
If you happen to use Arch Linux there is an [AUR package](https://aur.archlinux.org/packages/spotifywm-git) that includes a startup script.
Confirmed to work with:
`quirk[Spotify:spotify] = FLOAT`
