### ISSUE TITLE
[Action] maximized window with maximize_toogle doesn't respects region_padding > 0

### ISSUE THREAD

**Issue by osimplex** [conformal/spectrwm#402]
If I switch to max layout, `region_padding` parameter is respected, what not happens with `maximiza_toggle`, the window takes all the region real state.

**Comment by osimplex** [comment]
Arch Linux - spectrwm `3.4.1-1`.

**Comment by Ramiferous** [comment]
> 
> 
> If I switch to max layout, `region_padding` parameter is respected, what not happens with `maximize_toggle`, the window takes all the region real state.

Someone correct me if I'm wrong, but I believe this is the intended behaviour. I think what you mean is that when you toggle through the layouts and you get to the `FULLSCREEN` layout you still have region_padding and gaps etc, but with `maximize_toggle` it will always take up the entire screen? This is what maximize is supposed to do. 

I suspect what you are wanting is to go from a tiling master/stack mode, select a specific window from the master/stack to be FULLSCREEN while keeping the region_padding? for this you can just cycle trough the layouts. I'm not sure if there is a way to select a window from the stack to become fullscreen (like a sort of fullscreen_toggle?).

If it helps, please see my feature request for a MAXIMIZE quirk so that even when using region padding and gaps you can set specific windows to maximize by default. Perhaps a work around for what you want could be a a request for a NEVER_MAXIMIZE quirk so that the maximize_toggle become a pseudo fullscreen_toggle ??

**Comment by osimplex** [comment]
> Someone correct me if I'm wrong, but I believe this is the intended behaviour. I think what you mean is that when you toggle through the layouts and you get to the FULLSCREEN layout you still have region_padding, but with maximize_toggle it will always take up the entire screen? This is what maximize is supposed to do.

The problem is: spectrwm honors the _true_ fullscreen hint from windows, as you can see with F11 on Firefox. Also there is 'fullscreen_toggle' action, according to manual.

Manual says: "maximize_toggle: Toggle maximization of focused window". I use this when I not will switch the layout, so, when I cycle, maximized window is tiled as before, then focus goes to next tiled window. The point is: `max != fullscreen`, because the current squeme is pretty consistent for me, just this little thing that didn't see before because:

```
tile_gap                = -2
region_padding          = 0
border_width            = 2
```

Now:
```
tile_gap                = 3
region_padding          = 3
border_width            = 2
```

In the old scheme, max layout current window is equal a "maximized" window. This was the expected behavior when I switched to `padding` and `gaps`.
