### ISSUE TITLE
[Feature request] Determizable left/right part of the bar.

### ISSUE THREAD

**Issue by TCH69** [conformal/spectrwm#403]
So, can you add something like "+|L(40%) +|R(-*)" to the bar, so the left part gets 40% size of the bar, and the right part gets the rest? I always have more things (like the baraction script) in the right than in the left, so separating the bar in the middle is not a great idea.
![example](https://user-images.githubusercontent.com/44942508/96424554-0f04e100-1225-11eb-8f85-eb24489fbd18.jpg)

**Comment by LordReg** [comment]
This is already possible.

You can collapse a section to fit the text with `+|T` and the rest of the bar will go to the other section(s).
For example, a three-section bar with the left and right sections fitting the text and the rest given to the center for the window title:
```
bar_format = +|T+S{+L}{+M}+F+|C+W+|T%a %y-%m-%d %R
```
Also, weights can be specified to adjust the ratio of space allocated for L/C/R sections.
For example, a two-section bar with left section 40% and 60% for right section:
```
bar_format = +|4L+S{+L}{+M}+F +W+|10R+A | %a %y-%m-%d %R
```
You can also limit the length of character sequence output.  For example, `+40W` will limit the window title to 40 characters.  Underscore `_` can be added before/after/both to pad the length so that it doesn't change.
