### ISSUE TITLE
Issue starting the program:

### ISSUE THREAD

**Issue by sgreenden** [conformal/spectrwm#440]
The archwiki mentioned that you need to specify some supported font, however I am using the exact font they said was supported for testing purposes and I am still getting this error.

spectrwm: Welcome to spectrwm V3.4.1 Build: 3.4.1
/usr/local/bin/dmenu_run
/usr/bin/xterm
/usr/bin/xlock
spectrwm: Unable to load charset(s):
spectrwm: ISO8859-1
spectrwm: ISO8859-1
spectrwm: ISO8859-2
spectrwm: ISO8859-3
spectrwm: ISO8859-4
spectrwm: ISO8859-5
spectrwm: KOI8-R
spectrwm: ISO8859-7
spectrwm: ISO8859-9
spectrwm: ISO8859-13
spectrwm: ISO8859-14
spectrwm: ISO8859-15
spectrwm: JISX0208.1983-0
spectrwm: KSC5601.1987-0
spectrwm: GB2312.1980-0
spectrwm: JISX0201.1976-0
spectrwm: ISO10646-1
spectrwm: Error creating font set structure.

**Comment by DrakoDom** [comment]
Do you have your language specified in your `xinitrc` file? Assuming your system language is en_US, make sure you add `export LANG=en_US.UTF-8` before `exec spectrwm`

**Comment by LordReg** [comment]
Also ensure the font actually exists in the output of `fc-list`.

**Comment by Eccomi21** [comment]
I am having the same or a similar issue

1. I copied the standard conf from 
`/etc/spectrwm.conf` 
to 
`/home/eccomi/.spectrwm.conf`
Which is where I made all my edits in. 

2. I looked for the terminus font with 
`fc-list | grep -i terminus`
and made sure xos4 Terminus is installed.
I had both xos4 Terminus and non-xos4 Terminus Regular/Bold installed. I tried the config with both.

3. I then installed ttf-hack and repeated step 2

I specified my language in the `.xinitrc` file as mentioned above by @DrakoDom, making it look like this:

`export LANG=en_US.UTF-8
exec spectrwm`

From what I can tell `exec` isn't needed but I included it for good measure.

Yet no matter what font I try I get the exact same error. Fresh arch install and everything.

Any ideas?

**Comment by LordReg** [comment]
@Eccomi21 If you are getting the "Unable to load charset(s)" error with `bar_font = Terminus:pixelsize=14:antialias=true`, then it appears your conf isn't being loaded since you would get a different error if spectrwm fails to load an Xft `bar_font` setting.

Maybe spectrwm found a higher priority conf somewhere (e.g. `~/.config/spectrwm/spectrwm.conf`) or it's unable to access your conf. You could also try using the `-c` flag to ensure spectrwm only tries to load the conf you specify.

**Comment by Eccomi21** [comment]
> @Eccomi21 If you are getting the "Unable to load charset(s)" error with `bar_font = Terminus:pixelsize=14:antialias=true`, then it appears your conf isn't being loaded since you would get a different error if spectrwm fails to load an Xft `bar_font` setting.
> 
> Maybe spectrwm found a higher priority conf somewhere (e.g. `~/.config/spectrwm/spectrwm.conf`) or it's unable to access your conf. You could also try using the `-c` flag to ensure spectrwm only tries to load the conf you specify.

Firstly, that's the exact error I am getting. 
Is there a way to see which config it loads when starting up?

I found 3 config files with
`sudo find / -name '*spectrwm.conf*'`

/home/eccomi/.spectrwm.conf
/usr/etc/spectrwm.conf
/etc/spectrwm.conf 

All 3 have the exact same variable set.
`# bar_font = Terminus:pixelsize=14:antialias=true`
They used to have xos4 in front of Terminus after install with pacman but I changed that to see if it would work with the "old" terminus. It doesn't. 

Since I am getting the same error I can only assume it doesn't load any config at all.
You mentioned I could use the -c flag to specify which config it uses. I am assuming I'd append that when I call spectrwm in my .xinitrc, for example:

`exec spectrwm -c /home/eccomi/.spectrwm.conf`

I have to ask because I never used a flag like that.

I'll check out the wiki after replying and if I find how to do that there will edit this question out. Only got my phone rn otherwise I'd be looking it up before posting.

**Comment by LordReg** [comment]
Yes, `exec spectrwm -c /path/to/conf` works, with or without the `exec`.

I see the setting you quoted is commented out with a `#`. So, I have to ask, did you uncomment the setting in your `/home/eccomi/.spectrwm.conf`?

**Comment by Eccomi21** [comment]
> Yes, `exec spectrwm -c /path/to/conf` works, with or without the `exec`.
> 
> I see the setting you quoted is commented out with a `#`. So, I have to ask, did you uncomment the setting in your `/home/eccomi/.spectrwm.conf`?

Of course I did not. That would've been the smart thing to do...
Issue closed on my end. I completely forgot that different languages comment out lines with different Syntax. Hint could've been the literal comments at the top.
