### ISSUE TITLE
fix screen tearing in gaming and dropdown fps

### ISSUE THREAD

**Issue by enino13** [conformal/spectrwm#466]
really i love specrtwm and wanna do every thing on it gaming every thing

**Comment by c0dev0id** [comment]
How to you think this is related to spectrwm? Screen tearing can likely be handled by xorg depending on your graphics driver. An FPS drop is unlikely due to spectrwm. You'd need to add a lot more information about what you observe, what you expect and how you tested it and where it works better in comparism to spectrwm.

**Comment by enino13** [comment]
I made new test xubuntu spectrwm 3.4.1 it runs perfect I think debian run
older spectrwm 3.2 that's it spectrwm is my best tiling WM and thank you

**Comment by chent7** [comment]
Please close if there are no further related issues.
