### ISSUE TITLE
ctrl+click does not work in darktable

### ISSUE THREAD

**Issue by blitzgneisserin** [conformal/spectrwm#492]
Hi,

I am reporting this here although it could be a darktable issue as well, but probably the darktable devs won't look into it because I am the only darktable user who uses SpectrWM.

The problem is this: in the photo workflow app darktable, selecting multiple photos (thumbnails in lighttable mode) does not work. ctrl+click has the same result as simple click. In addition, in darktable mode, adjusting the brush with ctrl+scroll and shift+scroll does not work either.

I have tested this in several different window managers and desktop environments such as KDE Plasma or Awesome WM. Ctrl+click (etc.) do work everywhere but SpectrWM. However, in darktable/lighttable mode, ctrl+a for selecting all photos does work.
Ctrl+click does work in other apps such as graphical file managers.

System is Debian 11 + Nvidia graphics.

https://github.com/darktable-org/darktable/issues/10886#issue-1103311087

Thanks in advance for looking into this.

**Comment by LordReg** [comment]
This is an application issue related to ICCCM 6.3. Compliant window managers may establish button grabs (especially click-to-focus) on parent/root windows. Applications that do not take this into account may assume the user actually moved the pointer out of its window when the user clicks.

Since this isn't an isolated issue, there is now a workaround in master.
