### ISSUE TITLE
Getting a black screen then kicks me back out to lightdm

### ISSUE THREAD

**Issue by h8uthemost** [conformal/spectrwm#507]
That's pretty much my problem. I'm using Manjaro, and I've been using spectrwm for years, but I was always using it on a Debian based distro.

I install with pacman, that's no problem. And spectrwm shows up in my list of DE/WM's on LightDM. When I try to log into spectrwm I get the default Manjaro wallpaper for a sec, then a black screen. Then I"m kicked back out to LightDM. 

I've been having this problem for months. I've asked for help in other places, and a no-go. So I thought I'd try here. Funny thing though, in the AUR there's a package called sscrotwm. It's a "stripped down" version of spectrwm. Not even a bar. But the fact is that sscrotwm works just fine! I log into it from LightDM, and boom, I'm in scrot. But I want to be back in spectrwm.

I hope I've given enough info to help you to help me.

Thanks

**Comment by LordReg** [comment]
Are you running on defaults? It's likely the default bar fonts are failing to load. You may need to set `bar_font` so that spectrwm uses Xft for fonts. For example, if you have Terminus font installed:
`bar_font = Terminus:pixelsize=14:antialias=true`
If it still fails to start, you could try running spectrwm from the command line and capture any errors to a log file:
`startx spectrwm > ~/spectrwm.log 2>&1`

**Comment by h8uthemost** [comment]
Thanks for the reply.

Unfortunately I haven't gotten any farther. I have Terminus font installed, so I don't know why I"m still getting kicked out of it. And I tried running: `startx spectrwm > ~/spectrwm.log 2>&1` from a terminal, and it spits out a .log, but there's nothing in it. Unless I'm probably not using your directions correctly...

Thanks for trying to help me, but I think I'm to just use sscrotwm. Which is weird, like I said it doesn't have a bar, but it still has a bar_font section with this next to it: `-*-terminus-medium-*-*-*-*-*-*-*-*-*-*-*`

**Comment by LordReg** [comment]
I tested spectrwm on Manjaro Xfce Desktop full image and confirmed the issue.

spectrwm fails to start because Xlib is unable to load a font for the default locale. It will start if you change the locale to `C` in the LightDM locale menu.
Alternatively, you can make spectrwm use Xft for fonts by setting `bar_font` in spectrwm.conf. e.g.:
`bar_font = xos Terminus:pixelsize=14:antialias=true`
(Manjaro comes with `terminus-font` preinstalled. It is listed as `xos Terminus`, not `Terminus`.)

Also, `spectrwm` (or `spectrwm-git`<sup>AUR</sup> for latest) requires `xterm` and `xlockmore` for the default `term` and `lock` actions. They are not listed as dependencies since you can choose to install them or override `program[term]` and `program[lock]` in spectrwm.conf to use different programs.

**Comment by h8uthemost** [comment]
I'm glad you were able to confirm the issue, as far as getting spectrwm to work on your computer. 

But I tried everything you did and still I get kicked out of it. No matter if it's `spectrwm` or `spectrwm-git`. I changed my locale to C in the locale menu in LightDM, and that was a no-go. Then I tried changing my bar_font to `xos Terminus:pixelsize=14:antialias=true`. I've tried this in the config file(spectrwm.conf) in the /etc/ folder. And I've tried copying the file to my home and renaming it to `.spectrwm.conf`, as well as using `xos Terminus:pixelsize=14:antialias=true` in bar_font again.

Can you see any errors in what I'm doing?

And thank you for going to the lengths as installing manjaro and trying this out on your end. It's appreciated.

**Comment by LordReg** [comment]
I mistyped, it should be `xos4 Terminus`, so in your `~/.spectrwm.conf`:
`bar_font = xos4 Terminus:pixelsize=14:antialias=true`

You can see the available fonts and the names to use in `bar_font` by running `fc-list` in a terminal.

The C locale worked when I tested on the live image, it did not once I installed and updated. So, setting `bar_font` to one listed in the output of `fc-list` is the best solution at this time.

**Comment by h8uthemost** [comment]
`xos4 Terminus` comes as default when I install the WM. Now in Manjaro, Octopi is showing that font name is `terminus-font`. But that didn't work either.

I have no idea what I'm not doing wrong. That's ok, I'll use sscrotwm or i3 until this has been fixed and updated.

I appreciate all your help. :)

**Comment by h8uthemost** [comment]
Well, I'm back. Any news on this? I have the spectrwm-git installed this time in Manjaro, but I'm still getting the same problem. I've been beating my head on my desk for the last two hours trying all kinds of fonts. 

`xos4 Terminus` still isn't working.

**Comment by LordReg** [comment]
`bar_font` now has a "fail-safe" in master. spectrwm should no longer exit when the default/conf `bar_font` fails to load.

It sounds like the setting wasn't even being read. If you copied /etc/spectrwm.conf to ~/.spectrwm.conf, did you uncomment the `bar_font` setting by removing the leading '#'?

**Comment by h8uthemost** [comment]
This can finally now be closed. Un-commenting bar_font on the latest git release has solved it for me. 
Thank you LordReg.
