### ISSUE TITLE
wrong workspace for programs started from xfce4-terminal

### ISSUE THREAD

**Issue by christophgil** [conformal/spectrwm#508]
Thanks for this excellent WM!

When I launch X11 programs from the command line like xeyes they will appear at the Workspace where 
the first xfce4-terminal was launched instead of the current WS.

This might be because running xfce4-terminal does not create an own instance of xfce4-terminal.
Consequently, the PID of  xfce4-terminal will guide spectrwm to the wrong workspace.

Workaround: When starting xfce4 terminals with the following line,  things are fine. 
    /usr/bin/xfce4-terminal --disable-server

Another minor issue is that the workspace numbers start counting at 1 and are shifted with regard to
wmctrl -l
I use this command to identify the WS of a Window.
AFAIK, spectrwm does not have its own method to find and jump to Windows?

Cheers

Christoph

**Comment by vacuumbeef** [comment]
Looks like I encountered the same problem with alacritty terminal. I have the same problem when opening nsxiv and mpv.

**Comment by LordReg** [comment]
See the `SWMHACK` section of the man page (added in 3.5.1) for more information about *spawn-in-workspace* behavior and possible workarounds to these sort of issues.

As for the workspace numbering, spectrwm counts from 1, to match the default number key bindings. `wmctrl` is different because Extended Window Manager Hints `_NET_WM_DESKTOP` counts from 0.

It is possible to find/jump to windows by using the `search_win` action (M-f).
